### ISSUE TITLE
Is this still supported?

### ISSUE THREAD

**Issue by johnfg2610** [ChillyFlashER/Voreeal#1]
Hello, im looking to use a voxel terrain in my game but dont know c++ at all. are you still supporting/ working on this? i hope so! if so what version does it currently support and how would i compile it, also does it have BP support?
thank you for your time, johnfg12

**Comment by erictuvesson** [comment]
Hey, funny that you ask, I have been doing some work on it the past few days just haven't published any of the work yet (was hoping to do a big update all at once). I still have some work to do on the octree, mostly because am not fully sure on how I would like it to work and if there is something better I can do with PolyVox so the performance is better and memory allocation. 
The octree is also quite sensitive since I might change the internal storage to be depending on that. 

Eric

**Comment by johnfg2610** [comment]
Perfect been trying to find something like this for months.
This supports smooth voxels doesn't it?

**Comment by erictuvesson** [comment]
[PolyVox](https://bitbucket.org/volumesoffun/polyvox) has support for **marching cubes**, but not **dual contouring**.

The goal of this plugin is to support both plain voxels and marching cubes.

**Comment by johnfg2610** [comment]
marching cubes should be perfect. Are you adding bp nodes for terrain damage act?

**Comment by erictuvesson** [comment]
Yes, I intend to expose all functions to blueprint.

**Comment by johnfg2610** [comment]
Thank you for taking the time to awnser my questions :)
